#!/usr/bin/env sh

set -eufo pipefail

log() {
    case "$1" in
        info)
            shift
            echo "info: $*"
            ;;
        warn)
            shift
            echo "warn: $*"
            ;;
        fatal)
            shift
            echo "fatal: $*"
            exit 1
            ;;
    esac
}

tz=$(curl --silent --fail https://ipapi.co/timezone)
log info "remote timezone: ${tz}"

if [ -n "$tz" ]; then
  current=$(timedatectl status | awk -F' ' '/Time zone/ {print $3}')

  if [ ! -n "$current" ]; then
    log fatal "failed to detect current timezone"
  fi

  log info "local timezone: ${current}"

  if ! diff <(printf "$tz") <(printf "$current") >/dev/null 2>&1; then
    if timedatectl --no-ask-password set-timezone "$tz" >/dev/null 2>&1; then
      log info "successfully updated timezone: ${tz}"
    else
      log fatal "failed to set new timezone: ${tz}"
    fi
  fi
else
  log fatal "failed to detect timezone via remote call"
fi
