{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN pacman -Sy --noconfirm python2 sudo && \
    ln -sf /usr/bin/python2 /usr/bin/python
